# Generated by Django 2.2.5 on 2021-01-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationName', models.CharField(max_length=100)),
                ('CeoName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
