# Generated by Django 2.2.5 on 2021-01-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone_number', models.IntegerField(max_length=12)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
